[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "icbuilder"
version = "0.1"
dependencies = [
    "apexpy",
    "icreader @ git+https://github.com/icSuite/icReader.git@modular_pipeline",
    "netCDF4",
    "numba",
    "numpy",
    "scipy",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["icbuilder"]

[tool.setuptools.package-data]
icbuilder = ["data/*.nc", "data/*.json", "data/*.md"]
